/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulatiocheck;

import javax.swing.JOptionPane;

/**
 *
 * @author aluno.saolucas
 */
public class FormulatioCheck extends javax.swing.JFrame {

    /**
     * Creates new form FormulatioCheck
     */
    public FormulatioCheck() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcbManha = new javax.swing.JCheckBox();
        jcbTarde = new javax.swing.JCheckBox();
        jbEscolhaTurno = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jcbManha.setText("Manhã");
        jcbManha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbManhaActionPerformed(evt);
            }
        });

        jcbTarde.setText("Tarde");
        jcbTarde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbTardeActionPerformed(evt);
            }
        });

        jbEscolhaTurno.setText("ESCOLHA");
        jbEscolhaTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEscolhaTurnoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbManha)
                    .addComponent(jcbTarde))
                .addGap(61, 61, 61)
                .addComponent(jbEscolhaTurno)
                .addContainerGap(142, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jcbManha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcbTarde))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jbEscolhaTurno)))
                .addContainerGap(190, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbManhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbManhaActionPerformed
        jcbTarde.setSelected(false);
    }//GEN-LAST:event_jcbManhaActionPerformed

    private void jcbTardeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbTardeActionPerformed
        jcbManha.setSelected(false);
    }//GEN-LAST:event_jcbTardeActionPerformed

    private void jbEscolhaTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEscolhaTurnoActionPerformed
        if (jcbManha.isSelected()){
            JOptionPane.showMessageDialog(null,"Escolhido o Turno da"
                    +"Aviso ao Usuario"+ JOptionPane.INFORMATION_MESSAGE);
            
        }else if (jcbTarde.isSelected()){
            JOptionPane.showMessageDialog(null,"Escolhido o Turno da"
                    +"Aviso ao Usuario"+ JOptionPane.INFORMATION_MESSAGE);
            
        }else{
            JOptionPane.showMessageDialog(null,"ESCOLHA UMA DAS OPÇÕES"
                    +"Aviso ao Usuario"+ JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbEscolhaTurnoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormulatioCheck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormulatioCheck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormulatioCheck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormulatioCheck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormulatioCheck().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton jbEscolhaTurno;
    private javax.swing.JCheckBox jcbManha;
    private javax.swing.JCheckBox jcbTarde;
    // End of variables declaration//GEN-END:variables
}
