/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package radiobuton;

import javax.swing.JOptionPane;



/**
 *
 * @author aluno.saolucas
 */
public class FormularioBotao extends javax.swing.JFrame {

    /**
     * Creates new form FormularioBotao
     */
    public FormularioBotao() {
        initComponents();
        
        jrbCPF.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgselecao = new javax.swing.ButtonGroup();
        jrbCPF = new javax.swing.JRadioButton();
        jrbCNPJ = new javax.swing.JRadioButton();
        JbSELECIONAR = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bgselecao.add(jrbCPF);
        jrbCPF.setText("CPF");
        jrbCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbCPFActionPerformed(evt);
            }
        });

        bgselecao.add(jrbCNPJ);
        jrbCNPJ.setText("CNPJ");

        JbSELECIONAR.setText("SELECIONAR");
        JbSELECIONAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbSELECIONARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jrbCPF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                .addComponent(jrbCNPJ)
                .addGap(96, 96, 96))
            .addGroup(layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(JbSELECIONAR)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbCNPJ)
                    .addComponent(jrbCPF))
                .addGap(42, 42, 42)
                .addComponent(JbSELECIONAR)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrbCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbCPFActionPerformed

    private void JbSELECIONARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbSELECIONARActionPerformed
        String textoSelecionado = "";
        if(jrbCPF.isSelected()){
            textoSelecionado = "CPF SELECIONADO";
        }else if (jrbCNPJ.isSelected()){
              textoSelecionado = "CPNJ SELECIONADO";
       
        }
   JOptionPane.showMessageDialog(this,"Seleção realizada foi"+textoSelecionado);
    
  
    }//GEN-LAST:event_JbSELECIONARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioBotao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioBotao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioBotao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioBotao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioBotao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton JbSELECIONAR;
    private javax.swing.ButtonGroup bgselecao;
    private javax.swing.JRadioButton jrbCNPJ;
    private javax.swing.JRadioButton jrbCPF;
    // End of variables declaration//GEN-END:variables
}
